/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dominio.Mensaje;
import dominio.Usuario;
import implementacion.MensajeDAO;
import implementacion.UsuarioDAO;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.bson.types.ObjectId;

/**
 *
 * @author Antonio Moya
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        initComponents();
        llenarUsuarios();
        
    }
    
    
    public void llenarUsuarios(){
        UsuarioDAO dao = new UsuarioDAO();
        ArrayList<Usuario> usuarios = (ArrayList<Usuario>) dao.buscarTodas();
        for (int i = 0; i < usuarios.size(); i++) {            
            String correo = usuarios.get(i).getCorreo();          
//            Usuario objeto_especie = new Usuario(correo);
            this.cb_usuarios.addItem(correo);
        }
    }
    
    
    public void enviarMensaje(){
        UsuarioDAO dao = new UsuarioDAO();
        
        String mensaje = this.txt_mensaje.getText();
        Date fecha = new GregorianCalendar().getTime();
        ArrayList<Usuario> usuarios = (ArrayList<Usuario>) dao.buscarTodas();
         int ind = this.cb_usuarios.getSelectedIndex();
         
        Usuario usuario = usuarios.get(ind);
         
         
         
        ObjectId id = usuario.getId();
        
        
        Mensaje msj = new Mensaje(id, fecha, mensaje);
        new MensajeDAO().agregar(msj);
        this.llenarListaMensajes(this.obtenerMensajes());
    }
    
    public ArrayList<Mensaje> obtenerMensajes() {
       MensajeDAO mdao = new MensajeDAO();
        ArrayList<Mensaje> msjs = (ArrayList<Mensaje>) mdao.buscarTodas() ;
        return msjs;
    }
    public void llenarListaMensajes(ArrayList<Mensaje> mens) {
        Object mensajes[] = mens.toArray();
        this.listamsj.setModel(new javax.swing.AbstractListModel() {
            Object[] vect = mensajes;

            @Override
            public int getSize() {
                return vect.length;
            }

            @Override
            public Object getElementAt(int i) {
                return vect[i];
            }
        }
        );
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txt_mensaje = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        cb_usuarios = new javax.swing.JComboBox<>();
        btn_selec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_usuaSelect = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listamsj = new javax.swing.JList<>();

        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mensajeActionPerformed(evt);
            }
        });

        btn_enviar.setText("Enviar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        cb_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_usuariosActionPerformed(evt);
            }
        });

        btn_selec.setText("Seleccionar");
        btn_selec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecActionPerformed(evt);
            }
        });

        jLabel1.setText("Enviar a: ");

        txt_usuaSelect.setEditable(false);
        txt_usuaSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuaSelectActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(listamsj);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(txt_usuaSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_selec)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_enviar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_usuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selec, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_usuaSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enviar))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mensajeActionPerformed

    private void cb_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_usuariosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_usuariosActionPerformed

    private void btn_selecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecActionPerformed
        // TODO add your handling code here:
        
        
        this.txt_usuaSelect.setText(this.cb_usuarios.getSelectedItem().toString());
        this.llenarListaMensajes(this.obtenerMensajes());
        
    }//GEN-LAST:event_btn_selecActionPerformed

    private void txt_usuaSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuaSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuaSelectActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        // TODO add your handling code here:
        this.enviarMensaje();
    }//GEN-LAST:event_btn_enviarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_selec;
    private javax.swing.JComboBox<String> cb_usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listamsj;
    private javax.swing.JTextField txt_mensaje;
    private javax.swing.JTextField txt_usuaSelect;
    // End of variables declaration//GEN-END:variables
}
