/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package forms;

import dominio.Usuario;
import implementacion.UsuarioDAO;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio Moya
 */
public class Registrarse extends javax.swing.JFrame {

    /** Creates new form Registrarse */
    public Registrarse() {
        initComponents();
    }
    public boolean ValidarSoloLetras(String texto) {
        if (texto.matches("\\d*")) {
            return false;
        } else {
            return true;
        }
    }

    public boolean ValidarSoloNumeros(String texto) {

        if (texto.matches("\\d*")) {
            return true;
        } else {
            return false;
        }

    }
    
    public void vaciarCampos(){
        this.txt_corre.setText("");
        this.txt_telefono.setText("");
        this.txtp_contra.setText("");
        this.txtx_direccion.setText("");
        this.dt_fechaNacimiento.setText("");
        
    }
    
    public void registrar() {
        if (this.txt_corre.getText().equals("") ||this.txtx_direccion.getText().equals("") || this.txtp_contra.getText().equals("") || !ValidarSoloNumeros(this.txt_telefono.getText())) {

            JOptionPane.showMessageDialog(this, "LLene todos los campos correctamente", "Información", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String correo_electronico = this.txt_corre.getText();
        String contraseña = this.txtp_contra.getText();
        String direccion = this.txtx_direccion.getText();
        String telefono = this.txt_telefono.getText();
        String Sexo = (String) this.cb_sexo.getSelectedItem();
        LocalDate fechaNacimiento = this.dt_fechaNacimiento.getDate();

        
        Usuario usuarioNuevo = new Usuario(correo_electronico, telefono, contraseña, fechaNacimiento, direccion, Sexo);
        new UsuarioDAO().agregar(usuarioNuevo);
        JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");

        vaciarCampos();

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dt_fechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        txt_corre = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txtx_direccion = new javax.swing.JTextField();
        cb_sexo = new javax.swing.JComboBox<>();
        txtp_contra = new javax.swing.JPasswordField();
        btn_regirtrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Correo:");

        jLabel2.setText("Contraseña:");

        jLabel3.setText("Telefono:");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Sexo: ");

        jLabel6.setText("Fecha de nacimiento:");

        cb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino ", "Femeninio", "Robot", "Ninja", " " }));

        btn_regirtrar.setText("Registrar");
        btn_regirtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regirtrarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_atras.setText("Atras");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtp_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dt_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtx_direccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(txt_telefono, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_corre, javax.swing.GroupLayout.Alignment.LEADING))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(btn_regirtrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btn_atras)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_corre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtx_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dt_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtp_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_regirtrar))
                .addGap(18, 18, 18)
                .addComponent(btn_atras)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regirtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regirtrarActionPerformed
        // TODO add your handling code here:
        registrar();
    }//GEN-LAST:event_btn_regirtrarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        vaciarCampos();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        // TODO add your handling code here:
        IniciarSesion ini = new IniciarSesion();
        this.setVisible(false);
        ini.setVisible(true);
    }//GEN-LAST:event_btn_atrasActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_regirtrar;
    private javax.swing.JComboBox<String> cb_sexo;
    private com.github.lgooddatepicker.components.DatePicker dt_fechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_corre;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JPasswordField txtp_contra;
    private javax.swing.JTextField txtx_direccion;
    // End of variables declaration//GEN-END:variables

}
